beepmein: suppress unwanted stdout when run from at

diff --git a/bin/beepmein b/bin/beepmein
--- a/bin/beepmein
+++ b/bin/beepmein
@@ -172,10 +172,10 @@ playa () {
     [[ -f $file ]] || { superecho "file not found" ; return 1; }
     if command -v mpv >/dev/null 2>&1
     then
-        mpv --no-resume-playback --no-video "$file"
+        mpv --no-terminal --no-resume-playback --no-video "$file"
     elif command -v cvlc >/dev/null 2>&1
     then
-        cvlc --no-video "$file" vlc://quit
+        cvlc --quiet --no-video "$file" vlc://quit
     else
         superecho "no player"
         return 1
@@ -291,7 +291,7 @@ if [[ "$1" != "--reaction" ]] ; then
     (( setdelay )) && delay="$(date +%_S.%N)"
 
     # set 'at'
-    at "$attime" <<< "$(echo "sleep $delay; DISPLAY=${DISPLAY} beepmein --reaction $alarm '${reason}'")" &>/dev/null || { superecho "at input error." ; beep "2"; exit 1; } # beep two times for error
+    at -M "$attime" <<< "$(echo "sleep $delay; DISPLAY=${DISPLAY} /home/john/bin/beepmein --reaction $alarm '${reason}'")" &>/dev/null || { superecho "at input error." ; beep "2"; exit 1; } # beep two times for error
 
 else
     # reaction
