modified:   beepmein

diff --git a/bin/beepmein b/bin/beepmein
--- a/bin/beepmein
+++ b/bin/beepmein
@@ -208,11 +208,7 @@ if [[ "$1" == "--set-alarm" ]]; then
     if [[ -z "$2" ]]; then
         alarmpath="$(yad --on-top --center --title="Select alarm sample path" --file)"
     else
-<<<<<<< HEAD
         alarmpath="$(readlink -f -- "$2")" # must be absolute path
-=======
-        alarmpath="$(readlink -f "$2")" # must be absolute path
->>>>>>> 1ec651f1f30abf4dfd040d5335417c64e424c55a
     fi
     [[ -f "$alarmpath" ]] || { superecho "No valid alarm path given." ; beep "2"; exit 1; }
     # f=force
@@ -224,11 +220,7 @@ if [[ "$1" == "--set-remind" ]]; then
     if [[ -z "$2" ]]; then
         remindpath="$(yad --on-top --center --title="Select reminder sample path" --file)"
     else
-<<<<<<< HEAD
         remindpath="$(readlink -f -- "$2")" # must be absolute path
-=======
-        remindpath="$(readlink -f "$2")" # must be absolute path
->>>>>>> 1ec651f1f30abf4dfd040d5335417c64e424c55a
     fi
     [[ -f "$remindpath" ]] || { superecho "No valid reminder path given." ; beep "2"; exit 1; }
     # f=force
@@ -271,7 +263,7 @@ if [[ "$1" != "--reaction" ]] ; then
     (( setdelay )) && delay="$(date +%_S.%N)"
     
     # set 'at'
-    at "$attime" <<< "$(echo "sleep $delay; DISPLAY=${DISPLAY} beepmein --reaction $alarm '${reason}'")" > /dev/null 2>&1 || { superecho "at input error." ; beep "2"; exit 1; } # beep two times for error
+    at "$attime" <<< "$(echo "sleep $delay; DISPLAY=${DISPLAY} beepmein --reaction $alarm '${reason}'")" &>/dev/null || { superecho "at input error." ; beep "2"; exit 1; } # beep two times for error
     
 else
     # reaction
@@ -279,13 +271,12 @@ else
     if [ "$1" == "--alarm" ]; then
         shift
         notify-send "$1" &
-        #blink 1 0 >/dev/null 2>&1 &
-        blink 3 0.2 >/dev/null 2>&1 &
+        blink 3 0.2 &>/dev/null &
         playa "$alarmSample" || alarmfailsafe
         wait
     else
         notify-send "$1" &
-        blink 1 0 >/dev/null 2>&1 &
+        blink 1 0 &>/dev/null &
         playa "$reminderSample" || beep "3"
         wait
     fi
