bl-{conky,tint2}-session: allow absolute and relative paths

diff --git a/bin/bl-conky-session b/bin/bl-conky-session
--- a/bin/bl-conky-session
+++ b/bin/bl-conky-session
@@ -122,7 +122,7 @@ killConkys(){
 loadSession(){
     local sessfile CPATH_REGEX WMC_REGEX needRewrite conkys c path target
     sessfile=$1
-    CPATH_REGEX="-c '(.*(conky.*\.conf|conky|conkyrc))'([[:blank:]]+|$)"
+    CPATH_REGEX="-c[[:blank:]]+(.*(conky.*\.conf|conky|conkyrc))([[:blank:]]+|$)"
     WMC_REGEX='wmctrl -s ([0-9]{1,2})[[:blank:]]+'
     needRewrite=false
     mapfile -t conkys < "$sessfile"
@@ -164,6 +164,19 @@ loadSession(){
     done
 }
 
+fullPath(){
+    local path=$1
+    if [[ $path != /* ]]; then
+        if [[ -r "$CONKYPATH/$path" ]]; then
+            path="$CONKYPATH/$path"
+        elif [[ -r "$HOME/$path" ]]; then
+            path="$HOME/$path"
+        fi
+    fi
+    [[ -r $path ]] || { echo "$0: WARNING: cannot read $path" >&2 ; return 1;}
+    printf '%s' "$path"
+}
+
 launchConkys(){
     local WINID_REGEX path desktop datafile
     WINID_REGEX='drawing to created window \((0[xX][0-9a-fA-F]+)\)'
@@ -171,11 +184,11 @@ launchConkys(){
     set -m # enable job control so forked conkys are immune to signals (although unnecessary when conky is forked to background in config)
     for path in "${!ALL_CONKYS[@]}"; do
         case ${path%% *} in # first word
-        D\[*\]) # D[1]... is assumed to be a sufficiently unlikely beginning of a conky filepath
+        D\[*\]) # D[1]<space> is assumed to be a sufficiently unlikely beginning of a conky filepath
             desktop=${path%%]*}
             desktop=${desktop#*[}
             path=${path#* }
-            [[ -r $path ]] || { echo "$0: WARNING: cannot read $path" >&2 ; continue;}
+            path=$( fullPath "$path" ) || continue
             datafile=$(mktemp)
             conky -c "$path" >> "$datafile" 2>&1 &
             disown
@@ -185,7 +198,7 @@ launchConkys(){
             rm "$datafile"
             ;;
         *) # assume line is a clean filepath
-            [[ -r $path ]] || { echo "$0: WARNING: cannot read $path" >&2 ; continue;}
+            path=$( fullPath "$path" ) || continue
             conky -c "$path" >/dev/null 2>&1 &
             disown
             sleep 0.5
diff --git a/bin/bl-tint2-session b/bin/bl-tint2-session
--- a/bin/bl-tint2-session
+++ b/bin/bl-tint2-session
@@ -45,6 +45,8 @@ If a filepath is passed it is used as the session file,
 multiple sessions can be loaded.
 
 If not absolute, sessionfile paths are assumed to be relative to ~/.config/tint2/
+Relative tint2 paths are checked against HOME and ~/.config/tint2/,
+with the latter having priority.
 
 To start the default tint2 session at login,
 add the following line to autostart:
@@ -90,6 +92,19 @@ findArgs(){
     done
 }
 
+fullPath(){
+    local path=$1
+    if [[ $path != /* ]]; then
+        if [[ -r "$TINT2PATH/$path" ]]; then
+            path="$TINT2PATH/$path"
+        elif [[ -r "$HOME/$path" ]]; then
+            path="$HOME/$path"
+        fi
+    fi
+    [[ -r $path ]] || { echo "$0: WARNING: cannot read $path" >&2 ; return 1;}
+    printf '%s' "$path"
+}
+
 loadSession(){
     local sessfile=$1
     [[ $sessfile = /* ]] || sessfile="$TINT2PATH/$sessfile" # was relative path
@@ -97,8 +112,7 @@ loadSession(){
         safeKill tint2
         set -m
         while read -r path;do
-            [[ $path = /* ]] || path="$TINT2PATH/$path" # was relative path
-            [[ -r $path ]] || { echo "$0: WARNING: cannot read $path" >&2 ; continue;}
+            path=$( fullPath "$path" ) || continue
             tint2 -c "$path" >/dev/null 2>&1 &
             disown
             sleep 0.5
@@ -112,7 +126,7 @@ loadSession(){
 
 ########################################################################
 
-if [[ ! -f $SESSIONFILE ]] ; then
+if [[ ! -f $SESSIONFILE ]]; then
     echo "$0: There is no default session file: ${SESSIONFILE}, generating now..." >&2
     if [[ -f $DEFAULTTINT2 ]]; then
         echo "$DEFAULTTINT2" > "$SESSIONFILE"
