bl-obthemes: add function upgradeBlobs to move user config files to new locations

diff --git a/bin/bl-obthemes b/bin/bl-obthemes
--- a/bin/bl-obthemes
+++ b/bin/bl-obthemes
@@ -252,6 +252,78 @@ PICKX="X configs"
 
 ### FUNCTIONS ##########################################################
 
+function upgradeBlobs(){
+    for i in "$USRCONFIGPATH"/*; do
+        [[ -d $i ]] || continue
+        mkdir -p "$i/user"
+        moveFile(){ # $1 is file, $2 is target dir
+            [[ -f "$2/${1##*/}" ]] && return 0
+            [[ -f "$1" ]] || {
+                echo "$0: Upgrading ${i}: WARNING Cannot move file ${1}, it does not exist" >&2
+                return 1
+            }
+            mkdir -p "$2"
+            mv "$1" "$2" || exit
+        }
+        moveDir(){
+            [[ -d "$2/${1##*/}" ]] && return 0
+            [[ -d "$1" ]] || {
+                echo "$0: Upgrading ${i}: WARNING Cannot move directory ${1}, it does not exist" >&2
+                return 1
+            }
+            mkdir -p "$2"
+            mv "$1" "$2" || exit
+        }
+        touch "$i/newsettings"
+        while read -r TAG VAL; do
+            home_marker='%USERHOME%'
+            case "$TAG" in
+                "[TINT2]"       )   printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[CONKY]"       )   printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[ICONS]"       )   printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[GTK]"         )   moveFile "$i/.gtkrc-2.0" "$i/user"
+                                    moveFile "$i/.gtkrc-2.0.mine" "$i/user"
+                                    moveFile "$i/xfce4-notifyd.xml" "$i/user/.config/xfce4/xfconf/xfce-perchannel-xml"
+                                    moveDir "$i/gtk-3.0" "$i/user/.config"
+                                    printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[OBTHEME]"     )   printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[BACKGROUND]"  )   if [[ $VAL = FEH ]];then
+                                        moveFile "$i/.fehbg" "$i/user"
+                                    else
+                                        moveFile "$i/bg-saved.cfg" "$i/user/.config/nitrogen"
+                                    fi
+                                    printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[DMENU]"       )   moveFile "$i/dmenu-bind.sh" "$i/user/.config/dmenu"
+                                    printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[LIGHTDM]"     )   printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[EXITRC]"      )   printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[XFILES]"      )   moveFile "$i/.Xresources" "$i/user"
+                                    moveFile "$i/.bashrc" "$i/user"
+                                    printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                "[TERMINATOR]"  )   moveFile "$i/config" "$i/user/.config/terminator"
+                                    printf '%s %s\n' '[Terminator]' '.config/terminator/config' >> "$i/newsettings"
+                                    ;;
+                '['*']'         )   printf '%s %s\n' "$TAG" "$VAL" >> "$i/newsettings"
+                                    ;;
+                *               )   echo -e "Upgrading ${i}: ${TAG}:  Unknown value!" >&2
+                                    continue
+                                    ;;
+            esac
+        done < "$i/settings.cfg"
+        mv -f "$i/newsettings" "$i/settings.cfg"
+    done
+}
+
 # Kill only with exact match, and only if process belongs to executor.
 # Usage: safeKill <processname>
 function safeKill() {
