bl-obthemes: editKeyfile(): backup edited files if necessary
Edit GTK2 file as well as GTK3.
Add some error checks, debug messages and comments.

diff --git a/bin/bl-obthemes b/bin/bl-obthemes
--- a/bin/bl-obthemes
+++ b/bin/bl-obthemes
@@ -567,7 +567,7 @@ parseKeyfile(){
 # editKeyfile [--gtk2] file name=value [name2=value2...]
 # --gtk2 puts quotes around written string values
 editKeyfile(){
-    local type=gtk3 file name value sed_pattern sed_replace sed_args
+    local type=gtk3 file bkp_file name value sed_pattern sed_replace sed_args
     [[ $1 = '--gtk2' ]] && {
         type=gtk2
         shift
@@ -575,7 +575,7 @@ editKeyfile(){
     [[ -f $1 ]] || { echo "$1 is not a file." >&2; return 1;}
     file=$1
     shift
-    parseKeyfile "$file" # generates KEYS for the two checks
+    parseKeyfile "$file" || { echo "$0: editKeyfile() Failed to parse ${file}." 2>&1; return 1;}# generates global KEYS for the two checks
     boolean_enum_re='^([01]|GTK_[[:upper:]_]*)$' # in GTK2 gtkrc files these values are not quoted
     sed_args=()
     while [[ $1 ]]; do
@@ -602,7 +602,16 @@ editKeyfile(){
         sed_args+=("-e")
         sed_args+=("s/$sed_pattern/$sed_replace/")
     done
-    (( ${#sed_args[@]} )) && sed "${sed_args[@]}" "$file" || { echo "$0: sed error" >&2; return 1;}
+    unset KEYS
+    (( ${#sed_args[@]} )) && {
+        needBackup "${file}" && {
+            bkp_file="${file}${BKP_SFX}"
+            cp "$file" "$bkp_file" || return 1
+            debug "made backup copy of $file"
+        }
+        sed "${sed_args[@]}" "$file" || { echo "$0: sed error" >&2; return 1;}
+    }
+    return 0
 }
 
 
@@ -1187,7 +1196,7 @@ function getGTKname(){ # get saved GTK3 theme name and Icon theme name
     local gtk3_settings gtktheme icontheme txt
     gtk3_settings="$CONFIGDIR/user/$GTK3/settings.ini"
     # parseKeyfile generates global associative array KEYS
-    parseKeyfile "$gtk3_settings" || { yad_warning "Failed to parse $gtk3_settings."; return 1;}
+    parseKeyfile "$gtk3_settings" || { echo "$0: getGTKname() Failed to parse $gtk3_settings." 2>&1; return 1;}
     gtktheme=${KEYS[gtk-theme-name]}
     echo "[GTK] $gtktheme" >> "$SETTINGS"
     icontheme=${KEYS[gtk-icon-theme-name]}
@@ -1552,9 +1561,12 @@ function checkICONS(){ # check if icon theme is still present
             rm "$retfile"
             if [[ "$retval" = 0 ]]
             then
+                debug "Icon package $pkg was installed."
                 return 0
             else
                 yad_warning "Package install failed."
+                debug "Icon package ${pkg}: install failed."
+                return 1
             fi
         fi
     fi
@@ -1601,23 +1613,26 @@ function checkGTK(){    # check if gtk theme is still present
 
 # restoreIcons <icontheme>
 # $1 is $VAL from restoreSettings()
-# This function is used only when not restoring GTK settings, icon theme is included there.
+# This function is needed only when not restoring GTK settings - icon theme is included there.
 function restoreIcons(){
-    local new_icon_theme new_gtk3_settings new_icon_theme
+    local new_icon_theme current_gtk3_settings current_gtk2_settings new_gtk3_settings new_icon_theme
 #    new_icon_theme=$1
+    current_gtk3_settings="$HOME/$GTK3/settings.ini"
+    current_gtk2_settings="$HOME/$GTK2"
     new_gtk3_settings="$THEMEPATH/user/$GTK3/settings.ini"
-    parseKeyfile "$new_gtk3_settings" # GTK settings will not be restored, reading icon theme only
+    parseKeyfile "$new_gtk3_settings" || { echo "$0: restoreIcons() Failed to parse $new_gtk3_settings." 2>&1; return 1;} # new GTK settings will not be restored, reading icon theme only
     new_icon_theme=${KEYS[gtk-icon-theme-name]}
+    unset KEYS
     debug "Setting icon theme $new_icon_theme found in $new_gtk3_settings"
     checkICONS "$new_icon_theme" || {
         local NOICOTXT="Icon theme <b>$new_icon_theme</b> not found\n\n  The current icon theme will be used."
         yad_warning "$NOICOTXT"
         debug "Icon theme $new_icon_theme was not found, continuing to use the current icon theme."
-        return 0
+        return 0 # return 1 would trigger an error message
     }
     debug "\nSetting icon theme to $new_icon_theme, GTK theme is unchanged."
-    editKeyfile "$current_gtk3_settings" "gtk-icon-theme-name=$new_icon_theme"
-    unset KEYS
+    editKeyfile "$current_gtk3_settings" "gtk-icon-theme-name=$new_icon_theme" || return 1
+    editKeyfile --gtk2 "$current_gtk2_settings" "gtk-icon-theme-name=$new_icon_theme" || return 1
     reloadGTK
 }
 
@@ -1628,28 +1643,31 @@ function restoreIcons(){
 #  (these could be parsed from "$THEMEPATH/user/$GTK3/settings.ini" instead)
 # option --noicons causes icon theme to be reset to current setting
 function restoreGTK(){
-    local restore_icons current_gtk3_settings new_gtk3_settings current_gtk_theme new_gtk_theme current_icon_theme new_icon_theme
+    local restore_icons current_gtk3_settings new_gtk3_settings current_gtk2_settings current_gtk_theme new_gtk_theme current_icon_theme new_icon_theme
     restore_icons=true
     [[ $1 = '--noicons' ]] && { restore_icons=false; debug "Not setting a new icon theme."; shift; }
 #    new_gtk_theme=$1
 #    [[ -n $2 ]] && new_icon_theme=$2
+    current_gtk2_settings="$HOME/$GTK2"
     current_gtk3_settings="$HOME/$GTK3/settings.ini"
     new_gtk3_settings="$THEMEPATH/user/$GTK3/settings.ini"
-    parseKeyfile "$current_gtk3_settings" # settings before restoring files with new theme
+    parseKeyfile "$current_gtk3_settings" || { echo "$0: restoreGTK() Failed to parse ${current_gtk3_settings}." 2>&1; return 1;} # settings before restoring files with new theme
     current_gtk_theme=${KEYS[gtk-theme-name]}
     current_icon_theme=${KEYS[gtk-icon-theme-name]}
+    unset KEYS
     debug "current gtk theme is ${current_gtk_theme}, icon theme is $current_icon_theme"
-    parseKeyfile "$new_gtk3_settings" # settings before restoring files with new theme
+    parseKeyfile "$new_gtk3_settings" || { echo "$0: restoreGTK() Failed to parse $new_gtk3_settings." 2>&1; return 1;} # settings after restoring files with new theme
     new_gtk_theme=${KEYS[gtk-theme-name]}
     new_icon_theme=${KEYS[gtk-icon-theme-name]}
-
+    unset KEYS
     debug "Setting GTK theme $new_gtk_theme found in $new_gtk3_settings"
+
     checkGTK "$new_gtk_theme" || {
         local NOGTKTXT="GTK theme <b>$new_gtk_theme</b> not found\n\n  Continue with the current GTK theme, or exit?"
         if yad_warning_option "$NOGTKTXT"; then
             debug "$new_gtk_theme not found, continuing with current GTK theme $current_gtk_theme"
             if [[ $restore_icons = 'true' ]]; then
-                debug "icon theme will be restored"
+                debug "icon theme $new_icon_theme will be restored"
                 restoreIcons "$new_icon_theme" || return 1
             fi
             return 0
@@ -1669,12 +1687,13 @@ function restoreGTK(){
 
     safeKill jgmenu # If jgmenu is not running, GTK3 file edit will not trigger hook.
     restoreFiles "$GTK2" "$GTK2MINE" "$GTK3" "$GTK3x"
-    # $HOME/$GTK3/settings.ini has now been updated, need to parse again
+    # $HOME/$GTK3/settings.ini has now been updated
     [[ $restore_icons = 'false' ]] && {
         debug "Setting icon theme back to current $current_icon_theme"
-        editKeyfile "$current_gtk3_settings" "gtk-icon-theme-name=$current_icon_theme"
+        editKeyfile "$current_gtk3_settings" "gtk-icon-theme-name=$current_icon_theme" || return 1
+        editKeyfile --gtk2 "$current_gtk2_settings" "gtk-icon-theme-name=$current_icon_theme" || return 1
+
     }
-    unset KEYS # global KEYS is set by parseKeyfile in editKeyfile
     # If jgmenu cache is set, restart will not trigger GTK sync.
     # This means GTK sync will have to be done in this script, if wanted.
     # Currently done in restoreSettings().
@@ -1698,7 +1717,7 @@ function jgmenu_write_gtkcache(){
     local gtktheme jgmenu_cachedir
     jgmenu_cachedir="$HOME/.cache/jgmenu"
     mkdir -p "$jgmenu_cachedir"
-    parseKeyfile "$1" || { yad_warning "Failed to parse $1."; return 1;}
+    parseKeyfile "$1" || { echo "$0: jgmenu_write_gtkcache() Failed to parse $1" 2>&1; return 1;}
     gtktheme=${KEYS[gtk-theme-name]}
     debug "Setting $gtktheme as GTK theme in jgmenu cache."
     printf '%s' "$gtktheme" > "$jgmenu_cachedir/.last-gtktheme"
@@ -2032,7 +2051,7 @@ needBackup(){
                 return 1
             }
         else
-            diff -BEbZ "$file" "$blobfile" >/dev/null && {
+            diff -qBEbZ "$file" "$blobfile" >/dev/null && {
                 debug "$file has identical copy ${blobfile}, no need to backup"
                 return 1
             }
@@ -2292,12 +2311,12 @@ restoreSettings() {
         esac
     done <<< "$CHOICE"
     
-    if [[ $restore_gtk != 'false' ]]; then
+    if [[ $restore_gtk != 'false' ]]; then # restoring GTK theme
         if [[ $restore_icons != 'false' ]]; then
             restoreGTK "$restore_gtk" "$restore_icons" # restoreGTK will restore GTK settings including icons
             jgmenu_sync_gtk=true
         else
-            restoreGTK --noicons "$restore_gtk" # icon theme will be reset to current theme
+            restoreGTK --noicons "$restore_gtk" # icon theme will be reset to current theme by restoreGTK
             jgmenu_sync_gtk=true
         fi
     else
