Now uses 'tint2-sessionfile'; rewrite of session script to use functions and better checking

diff --git a/bl-tint2-session b/bl-tint2-session
--- a/bl-tint2-session
+++ b/bl-tint2-session
@@ -1,36 +1,69 @@
 #!/bin/bash
 ##
-#   Read a saved BunsenLabs tint2 session file and start the tint2s
+#   Read a saved BunsenLabs Tint2 session file and start the tint2s
 #
 #   written by <damo> for BunsenLabs, April 2015
 #
+#   To start the default Tint2 session at login, add the following line
+#   to config/openbox/autostart:
+#
+#      (sleep 2s && bl-tint2-session --autostart) &
+#
 ########################################################################
 TINT2PATH="$HOME/.config/tint2"
-SESSIONFILE="$TINT2PATH/tint2-session"
+SESSIONFILE="$TINT2PATH/tint2-sessionfile"
 USAGE=$(
     echo -e "\vUSAGE:  with no command argument, the script uses the default"
-    echo -e "\tTint2 session file \"$TINT2PATH/tint2-session.txt\""
+    echo -e "\tTint2 session file \"$TINT2PATH/tint2-sessionfile\""
     echo -e "\v\tTo start them at login, add the following line to autostart:"
-    echo -e "\v\t\t\"(sleep 2s && tint2-session) &\""
+    echo -e "\v\t\t\"(sleep 2s && bl-tint2-session --autostart) &\""
 )
 
-if [ $# -eq 0 ];then
-    if test -f "$1";then
-        if [ "$(pidof tint2)" ];then    # kill running tint2s
+findArgs(){     # get command args
+    i=0
+    for arg in "$@";do
+        if [[ $arg = "--autostart" ]];then
+            arg="$SESSIONFILE"
+            NOKILL=1    # run from autostart, so don't ask to kill tint2s
+            testSessionfile "$arg"
+        elif [[ $1 = "-h" ]] || [[ $1 = "--help" ]];then
+            echo "$USAGE"
+            exit 0
+        else
+            echo -e "\tERROR: sorry I don't understand the input"
+            echo "$USAGE"
+        fi
+    done
+}
+
+testSessionfile(){
+    if test -f  "$1" &>/dev/null;then # sessionfile found
+        if [[ $NOKILL == 0 ]];then # offer to stop running tint2s
+            killTints
+        fi
+        source "$1"     # run tint2s from sessionfile
+    else
+        echo "ERROR: sessionfile \"$1\" not found. Using default" >&2
+        tint2 &
+        exit 0
+    fi
+}
+
+killTints(){
+    if [ "$(pidof tint2)" ];then
+        msg="Kill running tint2s first?"
+        RET=$(zenity --question --text="$msg")
+        if [[ $? == 0 ]];then            # kill all tint2s
             killall tint2 && sleep 0.2s
         fi
-        source $SESSIONFILE
-    else
-        echo -e "\v\tERROR: SESSIONFILE \"$SESSIONFILE\" not found!" >&2
-        echo "$USAGE"
-        exit 1
     fi
-elif [[ $1 = "-h" ]] || [[ $1 = "--help" ]];then
-    echo "$USAGE"
-    exit 0
+}
+
+NOKILL=0
+if [ $# -eq 0 ];then    # if no args, then run default sessionfile
+    testSessionfile "$SESSIONFILE"    
 else
-    echo -e "\v\tWrong input!"
-    echo -e "\v\tUse \"bl-tint2-session [-h|--help]\"\v"
+    findArgs "$@"
 fi
 
 exit 0
